application: unvlille
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /
  static_files: static/index.html
  upload: static/(.*)

- url: /static
  static_dir: static

- url: .*
  script: main.py
