application: unvlille
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /
  static_files: static/index_stations.html
  upload: static/(.*)

- url: /static
  static_dir: static

- url: .*
  script: main.app